### ISSUE TITLE
Unable to use okto using Wallet connect

### ISSUE THREAD

**Issue by rajathongal** [WalletConnect/web3modal-examples#33]
Have been getting this error in console, okta works fine on pancakeswap using wallet connect but not in our dapp
This happens even in WC given examples https://github.com/WalletConnect/web3modal-examples/tree/main/web3modal-wagmi-react just add BSC chain select it and try to connect to okto it fails

But the same setup deployed here https://lab.web3modal.com/with-wagmi/react works with okto
```
Failed to launch 'okto://wc?uri=wc%3A652d1e7ca968a0368110ad024f2408aefb1d1f807eae22c5bc377c527f192367%402%3Frelay-protocol%3Dirn%26symKey%3Deec1a4bc8693a9bc63bff1a2ad6340df7758df9293766eb1dbc056be63b08b6a' 
because the scheme does not have a registered handler.
```

**Comment by rajathongal** [comment]
Locally it got connected after 20 mins and this still does not work with web3modal

**Comment by rajathongal** [comment]
![image](https://github.com/WalletConnect/web3modal-examples/assets/51845795/e24beb47-a205-495b-bcbc-ef6265be4505)
 above error is throwing and unable to connect to okto with same setup provided by WC mentioned the code repo in above comments

**Comment by 0xAsimetriq** [comment]
Judging by the screenshot your localStorage is full. We added few fixes for this in our latest sub-dependencies (I believe you are using wagmi, so updating to latest should help here). Launching `Failed to launch 'okto://wc?uri=wc%3A652d1e7ca968a0368110ad024f2408aefb1d1f807eae22c5bc377c527f192367%402%3Frelay-protocol%3Dirn%26symKey%3Deec1a4bc8693a9bc63bff1a2ad6340df7758df9293766eb1dbc056be63b08b6a' 
because the scheme does not have a registered handler.` means there is nothing on your device capable of handling this deeplink (either mobile or native deskto app.)

**Comment by 0xAsimetriq** [comment]
Closing this one via explanation above, as it is not example related issue. Work on this is being done in our sign-client package.
